image: python:3.5

test_app:
    script:
        - chmod +x utility/install*
        - utility/install_os_dependencies.sh
        - utility/install_python_dependencies.sh
        - wget https://bootstrap.pypa.io/get-pip.py --output-document=get-pip.py; chmod +x get-pip.py;  python3 get-pip.py
        - python manage.py test -k
