image: python:3.5

test_app:
    script:
        - apt-get -y install build-essential
        - apt-get -y install gettext
        - apt-get -y install python3-dev
        - apt-get -y install zlib1g-dev
        - apt-get -y install libpq-dev
        - apt-get -y install libtiff4-dev
        - apt-get -y install libjpeg8-dev
        - apt-get -y install libfreetype6-dev
        - apt-get -y install liblcms1-dev
        - apt-get -y install libwebp-dev
        - apt-get -y install graphviz-dev
        - wget https://bootstrap.pypa.io/get-pip.py --output-document=get-pip.py; chmod +x get-pip.py;  python3 get-pip.py
        - pip install -r $PROJECT_DIR/requirements/local.txt
        - pip install -r $PROJECT_DIR/requirements/test.txt
        - python manage.py test -k
