# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20170201_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ZIP code of final destination'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='riders',
            field=models.ManyToManyField(blank=True, related_name='riders', to=settings.AUTH_USER_MODEL),
        ),
    ]
