# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20170201_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
    ]
