# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import up_ride_finder.rides.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20170201_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=5, validators=[up_ride_finder.rides.validators.valid_zip], verbose_name='ZIP code of final destination'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin',
            field=models.CharField(max_length=5, validators=[up_ride_finder.rides.validators.valid_zip], verbose_name='ZIP code of origin'),
        ),
    ]
