# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_riderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.Ride'),
        ),
    ]
