# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20170320_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
